### ISSUE TITLE
Support for Julia

### ISSUE THREAD

**Issue by SWSAmor** [Exafunction/codeium-parse#20]
Is it good for that?
[Julia grammar for tree-sitter.](https://github.com/tree-sitter/tree-sitter-julia)
if true 
Pretty please. :-)

**Comment by pqn** [comment]
I could add the parser relatively quickly, but right now I can't prioritize the queries (but you're welcome to add them yourself of course).

**Comment by SWSAmor** [comment]
Thanks for the quick reply! I might give it a try, but I'm not entirely sure what needs to be done.

**Comment by pqn** [comment]
With the v0.0.12 release I've added a Julia parser. Some guidelines on how to write queries are here, if you get the time: https://github.com/Exafunction/codeium-parse#adding-and-testing-queries

I'll close this issue given that the Julia grammar is supported now.
