### ISSUE TITLE
Support for the Ada language 

### ISSUE THREAD

**Issue by elkarouh** [Exafunction/codeium-parse#7]
Hi,

Is it possible to add support for the Ada language 
https://github.com/briot/tree-sitter-ada

**Comment by pqn** [comment]
Feel free to run `./download_parse.sh` again and try it out!

**Comment by pqn** [comment]
> I get the following error message `I0310 06:52:48.000367 8096 main.go:119] Unspecified language received enry language Ada W0310 06:52:48.000448 8096 main.go:124] Unable to resolve enry language Ada W0310 06:52:48.000464 8096 main.go:191] unsupported language: LANGUAGE_UNSPECIFIED `

Auto-detection might not work with your file, but you can try to force a certain language with something like `-language ada`.

**Comment by pqn** [comment]
Oh I misread your error message, let me push a fix for this actually.

**Comment by pqn** [comment]
Feel free to try again with the latest (0.0.5).

**Comment by elkarouh** [comment]
It works.
Many thanks.

I will start experimenting and possibly report problems.
Great stuff !
